---
title: "Publications"
page-layout: article
---

## 2026

**20.** **Surface-tension-driven dynamic buckling and multimodal oscillations of inhomogeneous rod loops**, Y. Fang, C. Zhang, X. Li, Y. Man and X. Yi.
*Int. J. Mech. Sci.*, 325, 111841, 2026.

**19.** **Effect of shear-thinning on sphere's rotation-translation coupling inside a cylinder**, X. Liu, C. Zhu, Y. Man, J. Gao and Y. Chen.
*Acta Mech. Sin.*, 42(11), 325847, 2026.
[DOI](https://doi.org/10.1007/s10409-025-25847-x){target="_blank"}

**18.** **Directed swimming of Chlamydomonas reinhardtii near complex microstructures**, C. Li, H. Bian, Z. Lin, Y. Man and Z. Qu.
*Phys. Rev. E*, 113(4), 044410, 2026.
[DOI](https://doi.org/10.1103/gq4t-hpgz){target="_blank"}

## 2025

**17.** **Slip slender-body theory**, Y. Man, L. Koens and E. Lauga.
*J. Fluid Mech.*, vol. 1025, A34, 2025.
[PDF](files/papers/17.pdf){target="_blank"} | [DOI](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/abs/slip-slenderbody-theory/D373B1B62C0A25CB417F92D60ED11CCB){target="_blank"}

**16.** **Nutrient transport in concentration gradients**, J. Liu, Y. Man and E. Kanso.
*Phys. Rev. Fluids*, 10, 093104, 2025.
[PDF](files/papers/16.pdf){target="_blank"} | [DOI](https://journals.aps.org/prfluids/abstract/10.1103/7znc-3wzp){target="_blank"}

**15.** **Navigation of a three-link microswimmer via deep reinforcement learning**, Y. Lai, S. Heydari, O.S. Pak and Y. Man.
*Phys. Rev. Fluids*, 10, 064103, 2025.
[PDF](files/papers/15.pdf){target="_blank"} | [DOI](https://journals.aps.org/prfluids/abstract/10.1103/9msg-hgqn){target="_blank"}

**14.** **Trapping microswimmers in acoustic streaming flow**, X. Sun, W. Tan and Y. Man.
*J. Fluid Mech.*, vol. 1008, A32, 2025.
[PDF](files/papers/14.pdf){target="_blank"} | [DOI](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/abs/trapping-microswimmers-in-acoustic-streaming-flow/0FC0D924A48BFE83B0996BBFCAD584AD){target="_blank"}

**13.** **Optimal feeding in swimming and attached ciliates**, J. Liu, Y. Man, J.H. Costello and E. Kanso.
*J. Fluid Mech.*, vol. 1003, A26, 2025.
[PDF](files/papers/13.pdf){target="_blank"} | [DOI](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/optimal-feeding-in-swimming-and-attached-ciliates/3F6A9303063139B00426BA193E3C513E){target="_blank"}

## 2024

**12.** **Feeding rates in sessile versus motile ciliates are hydrodynamically equivalent**, J. Liu, Y. Man, J.H. Costello and E. Kanso.
*eLife*, 13:RP99003, 2024.
[PDF](files/papers/12.pdf){target="_blank"} | [DOI](https://elifesciences.org/reviewed-preprints/99003#){target="_blank"}

**11.** **Self-diffusiophoretic propulsion of a spheroidal particle in a shear-thinning fluid**, G. Zhu, B. vanGogh, L. Zhu, O.S. Pak and Y. Man.
*J. Fluid Mech.*, vol. 986, A39, 2024.
[PDF](files/papers/11.pdf){target="_blank"} | [DOI](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/selfdiffusiophoretic-propulsion-of-a-spheroidal-particle-in-a-shearthinning-fluid/27AC0443994A1186CC5682BF016950B9){target="_blank"}

**10.** **Hydrodynamic bound states of rotating microcylinders in a confining geometry**, H. Guo, Y. Man and H. Zhu.
*Phys. Rev. Fluids*, 9, 014102, 2024.
[PDF](files/papers/10.pdf){target="_blank"} | [DOI](https://journals.aps.org/prfluids/abstract/10.1103/PhysRevFluids.9.014102){target="_blank"}

## 2023 & Prior

**9.** **Evaluating evasion strategies in zebrafish Larvae**, Y. Jiao, B. Colvert, Y. Man, M. McHenry and E. Kanso.
*PNAS*, 120 (7), e2218909120, 2023.
[PDF](files/papers/9.pdf){target="_blank"} | [DOI](https://www.pnas.org/doi/10.1073/pnas.2218909120){target="_blank"}

**8.** **Intracellucar coupling modulates bifilagellar synchronization**, H. Guo, Y. Man, K-Y. Wan and E. Kanso.
*J. R. Soc. Interface*, 18, 20200660, 2021.
[PDF](files/papers/8.pdf){target="_blank"} | [DOI](https://royalsocietypublishing.org/doi/10.1098/rsif.2020.0660){target="_blank"}

**7.** **Multisynchrony in active microfilaments**, Y. Man and E. Kanso.
*Phys. Rev. Lett.* (Editor's Suggestion), 125, 148101, 2020.
[PDF](files/papers/7.pdf){target="_blank"} | [DOI](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.125.148101){target="_blank"}

**6.** **Cilia oscillations**, Y. Man, F. Ling and E. Kanso.
*Philos. Trans. R. Soc. B*, 375, 20190157, 2019.
[PDF](files/papers/6.pdf){target="_blank"} | [DOI](https://royalsocietypublishing.org/doi/10.1098/rstb.2019.0157){target="_blank"}

**5.** **Morphological transitions of axially-driven microfilaments**, Y. Man and E. Kanso.
*Soft Matter*, 15, 5163, 2019.
[PDF](files/papers/5.pdf){target="_blank"} | [DOI](https://royalsocietypublishing.org/doi/10.1098/rsif.2020.0660){target="_blank"}

**4.** **Bundling of elastic filaments from hydrodynamic interactions**, Y. Man, W. Page, R. Poole and E. Lauga.
*Phys. Rev. Fluids*, 2, 123101, 2017.
[PDF](files/papers/4.pdf){target="_blank"} | [DOI](https://journals.aps.org/prfluids/abstract/10.1103/PhysRevFluids.2.123101){target="_blank"}

**3.** **Hydrodynamic interactions between nearby slender filaments**, Y. Man, L. Koens and E. Lauga.
*Europhys. Lett.*, 116, 2, 2016.
[PDF](files/papers/3.pdf){target="_blank"} | [DOI](https://iopscience.iop.org/article/10.1209/0295-5075/116/24002){target="_blank"}

**2.** **Phase-separation models for swimming enhancement in complex fluids**, Y. Man and E. Lauga.
*Phys. Rev. E*, 92, 023004, 2015.
[PDF](files/papers/2.pdf){target="_blank"} | [DOI](https://royalsocietypublishing.org/doi/10.1098/rsif.2020.0660){target="_blank"}

**1.** **The wobbling-to-swimming transition of rotated helices**, Y. Man and E. Lauga.
*Phys. Fluids*, 25, 071904, 2013.
[PDF](files/papers/1.pdf){target="_blank"} | [DOI](https://aip.scitation.org/doi/10.1063/1.4812637){target="_blank"}

<br>
<hr>

## Ph.D. Thesis

**Swimming at low Reynolds number: slip boundaries and interacting filaments**, 
Y. Man,
*University of Cambridge*, 2017.
[PDF](files/papers/thesis_Man.pdf){target="_blank"} | [Library Link](https://www.repository.cam.ac.uk/items/3e1ac6c8-38ad-4e6f-abc3-40f4ff0586cc){target="_blank"}
